### PR TITLE
Update Deps

### PR DESCRIPTION
**Pull request by vladikoff**
@shama could you please add me to https://www.npmjs.com/package/grunt-legacy-log-utils npm list?

### CODE REVIEW

**Comment by vladikoff** [comment]
@tkellen @cowboy or maybe one of you is at a computer terminal at this time :)

**Comment by tkellen** [comment]
I just added you @vladikoff! Didn't think to check if this was done already, so, if it was, go ahead and ignore this :)

**Comment by tkellen** [comment]
PS: thanks for your continued stewardship of this project!

**Comment by vladikoff** [comment]
Thank you @tkellen !

**Comment by vladikoff** [comment]
> I just added you @vladikoff!

That didn't work :( 

https://www.npmjs.com/package/grunt-legacy-log-utils

**Comment by tkellen** [comment]
```
grunt-legacy-log-utils on  master is 📦 v2.0.0 via ⬢ v9.11.1 at ☸️ aevitas 
➜ npm author add vladikoff
+ vladikoff (grunt-legacy-log-utils)
```

**Comment by tkellen** [comment]
Can you check now?

**Comment by vladikoff** [comment]
@tkellen Yes! Thank you!

**Pull request merged**
